/**
 * FBR Testing Scenarios
 * 28 predefined scenarios for testing FBR invoice submission
 */

export const FBR_SCENARIOS = [
  {
    id: "SN001",
    name: "Sale of Standard Rate Goods to Registered Buyers",
    description: "Standard 18% tax rate for registered buyers",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "2046004",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Registered",
      invoiceRefNo: "",
      items: [{
        hsCode: "0101.2100",
        productDescription: "LIVE ANIMALS - LIVE HORSES, ASSES, MULES AND HINNIES - PUREBRED BREEDING ANIMALS",
        rate: "18%",
        uoM: "Numbers, pieces, units",
        quantity: 400,
        totalValues: 1180,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0.0,
        salesTaxApplicable: 180,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "",
        fedPayable: 0,
        discount: 0,
        saleType: "Goods at standard rate (default)",
        sroItemSerialNo: ""
      }]
    }
  },
  {
    id: "SN002",
    name: "Sale of Standard Rate Goods to Unregistered Buyers",
    description: "Standard rate for individual consumers (B2C)",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "1234567",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Unregistered",
      invoiceRefNo: "",
      items: [{
        hsCode: "0101.2100",
        productDescription: "LIVE ANIMALS - LIVE HORSES, ASSES, MULES AND HINNIES - PUREBRED BREEDING ANIMALS",
        rate: "18%",
        uoM: "Numbers, pieces, units",
        quantity: 400,
        totalValues: 1180,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0.0,
        salesTaxApplicable: 180,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "",
        fedPayable: 0,
        discount: 0,
        saleType: "Goods at standard rate (default)",
        sroItemSerialNo: ""
      }]
    }
  },
  {
    id: "SN003",
    name: "Sale of Steel (Melted and Re-Rolled)",
    description: "Steel sector with strict traceability",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "3710505701479",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Unregistered",
      invoiceRefNo: "",
      items: [{
        hsCode: "7214.1010",
        productDescription: "Steel billets, ingots and long bars",
        rate: "18%",
        uoM: "MT",
        quantity: 1,
        totalValues: 0,
        valueSalesExcludingST: 205000.00,
        fixedNotifiedValueOrRetailPrice: 0.0,
        salesTaxApplicable: 36900,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "",
        fedPayable: 0,
        discount: 0,
        saleType: "Steel melting and re-rolling",
        sroItemSerialNo: ""
      }]
    }
  },
  {
    id: "SN005",
    name: "Sales of Reduced Rate Goods (Eighth Schedule)",
    description: "Reduced tax rate for essential commodities",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-06-30",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "1000000000000",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Unregistered",
      invoiceRefNo: "",
      items: [{
        hsCode: "0102.2930",
        productDescription: "Essential food items",
        rate: "1%",
        uoM: "Numbers, pieces, units",
        quantity: 1.0,
        totalValues: 0.0,
        valueSalesExcludingST: 1000.0,
        fixedNotifiedValueOrRetailPrice: 0.0,
        salesTaxApplicable: 10,
        salesTaxWithheldAtSource: 50.23,
        extraTax: 0,
        furtherTax: 120.0,
        sroScheduleNo: "EIGHTH SCHEDULE Table 1",
        fedPayable: 50.36,
        discount: 56.36,
        saleType: "Goods at Reduced Rate",
        sroItemSerialNo: "82"
      }]
    }
  },
  {
    id: "SN006",
    name: "Sale of Exempt Goods (Sixth Schedule)",
    description: "Tax-exempt essential items",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-07-01",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "2046004",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Registered",
      invoiceRefNo: "",
      items: [{
        hsCode: "0102.2930",
        productDescription: "Exempt essential goods",
        rate: "Exempt",
        uoM: "Numbers, pieces, units",
        quantity: 1.0,
        totalValues: 0.0,
        valueSalesExcludingST: 10,
        fixedNotifiedValueOrRetailPrice: 0.0,
        salesTaxApplicable: 0,
        salesTaxWithheldAtSource: 50.23,
        extraTax: 0,
        furtherTax: 120.0,
        sroScheduleNo: "6th Schd Table I",
        fedPayable: 50.36,
        discount: 56.36,
        saleType: "Exempt goods",
        sroItemSerialNo: "100"
      }]
    }
  },
  {
    id: "SN007",
    name: "Sale Of Zero-Rated Goods (Fifth Schedule)",
    description: "0% tax but input credit allowed",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "3710505701479",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Unregistered",
      invoiceRefNo: "",
      items: [{
        hsCode: "0101.2100",
        productDescription: "Zero-rated exports",
        rate: "0%",
        uoM: "Numbers, pieces, units",
        quantity: 100,
        totalValues: 0,
        valueSalesExcludingST: 100,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 0,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "327(I)/2008",
        fedPayable: 0,
        discount: 0,
        saleType: "Goods at zero-rate",
        sroItemSerialNo: "1"
      }]
    }
  },
  {
    id: "SN008",
    name: "Sale of 3rd Schedule Goods",
    description: "Tax on retail price basis",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "3710505701479",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Unregistered",
      invoiceRefNo: "",
      items: [{
        hsCode: "0101.2100",
        productDescription: "Retail price based goods",
        rate: "18%",
        uoM: "Numbers, pieces, units",
        quantity: 100,
        totalValues: 145,
        valueSalesExcludingST: 0,
        fixedNotifiedValueOrRetailPrice: 1000,
        salesTaxApplicable: 180,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "",
        fedPayable: 0,
        discount: 0,
        saleType: "3rd Schedule Goods",
        sroItemSerialNo: ""
      }]
    }
  },
  {
    id: "SN004",
    name: "Sale of Fertilizer",
    description: "Fertilizer with specific tax treatment",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "2046004",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Registered",
      invoiceRefNo: "",
      items: [{
        hsCode: "3102.1000",
        productDescription: "Fertilizer products",
        rate: "10%",
        uoM: "MT",
        quantity: 10,
        totalValues: 0,
        valueSalesExcludingST: 50000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 5000,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "",
        fedPayable: 0,
        discount: 0,
        saleType: "Fertilizer",
        sroItemSerialNo: ""
      }]
    }
  },
  {
    id: "SN009",
    name: "Sale of POL Products",
    description: "Petroleum products with special rates",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "2046004",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Registered",
      invoiceRefNo: "",
      items: [{
        hsCode: "2710.1911",
        productDescription: "Petroleum oils and products",
        rate: "17%",
        uoM: "Liters",
        quantity: 1000,
        totalValues: 0,
        valueSalesExcludingST: 100000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 17000,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "",
        fedPayable: 0,
        discount: 0,
        saleType: "POL Products",
        sroItemSerialNo: ""
      }]
    }
  },
  {
    id: "SN010",
    name: "Sale of Cigarettes",
    description: "Tobacco products with FED",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "3710505701479",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Unregistered",
      invoiceRefNo: "",
      items: [{
        hsCode: "2402.2000",
        productDescription: "Cigarettes containing tobacco",
        rate: "18%",
        uoM: "Thousand",
        quantity: 10,
        totalValues: 0,
        valueSalesExcludingST: 50000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 9000,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "",
        fedPayable: 15000,
        discount: 0,
        saleType: "Cigarettes",
        sroItemSerialNo: ""
      }]
    }
  },
  {
    id: "SN011",
    name: "Sale of Cement",
    description: "Cement with withholding tax",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "2046004",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Registered",
      invoiceRefNo: "",
      items: [{
        hsCode: "2523.2900",
        productDescription: "Portland cement",
        rate: "17%",
        uoM: "MT",
        quantity: 100,
        totalValues: 0,
        valueSalesExcludingST: 500000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 85000,
        salesTaxWithheldAtSource: 2500,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "",
        fedPayable: 0,
        discount: 0,
        saleType: "Cement",
        sroItemSerialNo: ""
      }]
    }
  },
  {
    id: "SN012",
    name: "Sale of Edible Oil",
    description: "Edible oil with reduced rate",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "3710505701479",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Unregistered",
      invoiceRefNo: "",
      items: [{
        hsCode: "1507.1000",
        productDescription: "Soyabean oil and its fractions",
        rate: "8%",
        uoM: "Liters",
        quantity: 500,
        totalValues: 0,
        valueSalesExcludingST: 75000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 6000,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "EIGHTH SCHEDULE Table 1",
        fedPayable: 0,
        discount: 0,
        saleType: "Goods at Reduced Rate",
        sroItemSerialNo: "45"
      }]
    }
  },
  {
    id: "SN013",
    name: "Sale of Sugar",
    description: "Sugar with standard rate",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "2046004",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Registered",
      invoiceRefNo: "",
      items: [{
        hsCode: "1701.1400",
        productDescription: "Cane or beet sugar",
        rate: "18%",
        uoM: "KG",
        quantity: 5000,
        totalValues: 0,
        valueSalesExcludingST: 250000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 45000,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "",
        fedPayable: 0,
        discount: 0,
        saleType: "Goods at standard rate (default)",
        sroItemSerialNo: ""
      }]
    }
  },
  {
    id: "SN014",
    name: "Sale of Tea",
    description: "Tea with special provisions",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "3710505701479",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Unregistered",
      invoiceRefNo: "",
      items: [{
        hsCode: "0902.3000",
        productDescription: "Black tea (fermented)",
        rate: "18%",
        uoM: "KG",
        quantity: 100,
        totalValues: 0,
        valueSalesExcludingST: 50000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 9000,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "",
        fedPayable: 0,
        discount: 0,
        saleType: "Goods at standard rate (default)",
        sroItemSerialNo: ""
      }]
    }
  },
  {
    id: "SN015",
    name: "Sale of Textile Products",
    description: "Textile with export potential",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "2046004",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Registered",
      invoiceRefNo: "",
      items: [{
        hsCode: "5208.1100",
        productDescription: "Woven fabrics of cotton",
        rate: "18%",
        uoM: "Meters",
        quantity: 10000,
        totalValues: 0,
        valueSalesExcludingST: 500000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 90000,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "",
        fedPayable: 0,
        discount: 0,
        saleType: "Goods at standard rate (default)",
        sroItemSerialNo: ""
      }]
    }
  },
  {
    id: "SN016",
    name: "Sale of Mobile Phones",
    description: "Electronics with FED",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "3710505701479",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Unregistered",
      invoiceRefNo: "",
      items: [{
        hsCode: "8517.1200",
        productDescription: "Telephones for cellular networks",
        rate: "18%",
        uoM: "Numbers, pieces, units",
        quantity: 50,
        totalValues: 0,
        valueSalesExcludingST: 2500000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 450000,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "",
        fedPayable: 125000,
        discount: 0,
        saleType: "Goods at standard rate (default)",
        sroItemSerialNo: ""
      }]
    }
  },
  {
    id: "SN017",
    name: "Sale of Pharmaceuticals",
    description: "Medicine with exempt status",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "2046004",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Registered",
      invoiceRefNo: "",
      items: [{
        hsCode: "3003.2000",
        productDescription: "Medicaments containing antibiotics",
        rate: "Exempt",
        uoM: "Numbers, pieces, units",
        quantity: 1000,
        totalValues: 0,
        valueSalesExcludingST: 100000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 0,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "6th Schd Table I",
        fedPayable: 0,
        discount: 0,
        saleType: "Exempt goods",
        sroItemSerialNo: "25"
      }]
    }
  },
  {
    id: "SN018",
    name: "Sale of Books and Stationery",
    description: "Educational materials - exempt",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "3710505701479",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Unregistered",
      invoiceRefNo: "",
      items: [{
        hsCode: "4901.1000",
        productDescription: "Printed books, brochures, leaflets",
        rate: "Exempt",
        uoM: "Numbers, pieces, units",
        quantity: 500,
        totalValues: 0,
        valueSalesExcludingST: 25000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 0,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "6th Schd Table I",
        fedPayable: 0,
        discount: 0,
        saleType: "Exempt goods",
        sroItemSerialNo: "8"
      }]
    }
  },
  {
    id: "SN019",
    name: "Sale of Beverages",
    description: "Soft drinks with FED",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "2046004",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Registered",
      invoiceRefNo: "",
      items: [{
        hsCode: "2202.1000",
        productDescription: "Waters, including mineral and aerated",
        rate: "18%",
        uoM: "Liters",
        quantity: 5000,
        totalValues: 0,
        valueSalesExcludingST: 250000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 45000,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "",
        fedPayable: 37500,
        discount: 0,
        saleType: "Goods at standard rate (default)",
        sroItemSerialNo: ""
      }]
    }
  },
  {
    id: "SN020",
    name: "Sale of Automotive Parts",
    description: "Auto parts with standard rate",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "3710505701479",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Unregistered",
      invoiceRefNo: "",
      items: [{
        hsCode: "8708.2990",
        productDescription: "Parts and accessories of motor vehicles",
        rate: "18%",
        uoM: "Numbers, pieces, units",
        quantity: 100,
        totalValues: 0,
        valueSalesExcludingST: 300000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 54000,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "",
        fedPayable: 0,
        discount: 0,
        saleType: "Goods at standard rate (default)",
        sroItemSerialNo: ""
      }]
    }
  },
  {
    id: "SN021",
    name: "Sale of Dairy Products",
    description: "Milk products with reduced rate",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "2046004",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Registered",
      invoiceRefNo: "",
      items: [{
        hsCode: "0401.1000",
        productDescription: "Milk and cream, not concentrated",
        rate: "0%",
        uoM: "Liters",
        quantity: 1000,
        totalValues: 0,
        valueSalesExcludingST: 50000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 0,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "6th Schd Table I",
        fedPayable: 0,
        discount: 0,
        saleType: "Exempt goods",
        sroItemSerialNo: "1"
      }]
    }
  },
  {
    id: "SN022",
    name: "Sale of Electrical Appliances",
    description: "Home appliances with FED",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "3710505701479",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Unregistered",
      invoiceRefNo: "",
      items: [{
        hsCode: "8418.1000",
        productDescription: "Combined refrigerator-freezers",
        rate: "18%",
        uoM: "Numbers, pieces, units",
        quantity: 20,
        totalValues: 0,
        valueSalesExcludingST: 1000000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 180000,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "",
        fedPayable: 50000,
        discount: 0,
        saleType: "Goods at standard rate (default)",
        sroItemSerialNo: ""
      }]
    }
  },
  {
    id: "SN023",
    name: "Sale of Construction Materials",
    description: "Building materials",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "2046004",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Registered",
      invoiceRefNo: "",
      items: [{
        hsCode: "6810.1100",
        productDescription: "Building blocks and bricks",
        rate: "18%",
        uoM: "Thousand",
        quantity: 50,
        totalValues: 0,
        valueSalesExcludingST: 250000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 45000,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "",
        fedPayable: 0,
        discount: 0,
        saleType: "Goods at standard rate (default)",
        sroItemSerialNo: ""
      }]
    }
  },
  {
    id: "SN024",
    name: "Sale of Cosmetics",
    description: "Beauty products with luxury tax",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "3710505701479",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Unregistered",
      invoiceRefNo: "",
      items: [{
        hsCode: "3304.9900",
        productDescription: "Beauty or make-up preparations",
        rate: "18%",
        uoM: "Numbers, pieces, units",
        quantity: 500,
        totalValues: 0,
        valueSalesExcludingST: 150000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 27000,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "",
        fedPayable: 7500,
        discount: 0,
        saleType: "Goods at standard rate (default)",
        sroItemSerialNo: ""
      }]
    }
  },
  {
    id: "SN025",
    name: "Sale of Computer Equipment",
    description: "IT equipment standard rate",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "2046004",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Registered",
      invoiceRefNo: "",
      items: [{
        hsCode: "8471.3000",
        productDescription: "Portable automatic data processing machines",
        rate: "18%",
        uoM: "Numbers, pieces, units",
        quantity: 30,
        totalValues: 0,
        valueSalesExcludingST: 1500000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 270000,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "",
        fedPayable: 0,
        discount: 0,
        saleType: "Goods at standard rate (default)",
        sroItemSerialNo: ""
      }]
    }
  },
  {
    id: "SN026",
    name: "Sale of Footwear",
    description: "Shoes and sandals",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "3710505701479",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Unregistered",
      invoiceRefNo: "",
      items: [{
        hsCode: "6403.9900",
        productDescription: "Footwear with outer soles of rubber",
        rate: "18%",
        uoM: "Pairs",
        quantity: 1000,
        totalValues: 0,
        valueSalesExcludingST: 200000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 36000,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "",
        fedPayable: 0,
        discount: 0,
        saleType: "Goods at standard rate (default)",
        sroItemSerialNo: ""
      }]
    }
  },
  {
    id: "SN027",
    name: "Sale of Furniture",
    description: "Wooden furniture",
    data: {
      invoiceType: "Sale Invoice",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "2046004",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Registered",
      invoiceRefNo: "",
      items: [{
        hsCode: "9403.3000",
        productDescription: "Wooden furniture of a kind used in offices",
        rate: "18%",
        uoM: "Numbers, pieces, units",
        quantity: 50,
        totalValues: 0,
        valueSalesExcludingST: 750000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 135000,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "",
        fedPayable: 0,
        discount: 0,
        saleType: "Goods at standard rate (default)",
        sroItemSerialNo: ""
      }]
    }
  },
  {
    id: "SN028",
    name: "Debit Note - Price Adjustment",
    description: "Debit note for additional charges",
    data: {
      invoiceType: "Debit Note",
      invoiceDate: "2025-04-21",
      sellerBusinessName: "HAQ NAWAZ KARYANA MERCHANT",
      sellerProvince: "Punjab",
      sellerNTNCNIC: "3310009111359",
      sellerAddress: "Faisalabad",
      buyerNTNCNIC: "2046004",
      buyerBusinessName: "FERTILIZER MANUFAC IRS NEW",
      buyerProvince: "Sindh",
      buyerAddress: "Karachi",
      buyerRegistrationType: "Registered",
      invoiceRefNo: "INV-2025-0001",
      items: [{
        hsCode: "0101.2100",
        productDescription: "Price adjustment for previous invoice",
        rate: "18%",
        uoM: "Numbers, pieces, units",
        quantity: 100,
        totalValues: 0,
        valueSalesExcludingST: 5000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 900,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: "",
        fedPayable: 0,
        discount: 0,
        saleType: "Goods at standard rate (default)",
        sroItemSerialNo: ""
      }]
    }
  }
];

export const SCENARIO_MAP = FBR_SCENARIOS.reduce((acc, scenario) => {
  acc[scenario.id] = scenario;
  return acc;
}, {});

export default FBR_SCENARIOS;
